* Возможности

- Выбор любого;

- Выбор любой конфигурации линейных кораблей;

- Можно писать своих ботов расстановщиков и стрелков.

* Невозможности

- Нелинейные корабли;

- Проверка безопасности ботов;

- Проверка возможности существования данной конфигурации кораблей на
  данном поле.

* Сделано

- Принтер поля;

- Интерфейс для игры с человеком;

- [Более-менее] удобная расстановка кораблей для человека.

* Планируется

- История сражений и возможность для ботов ее читать и
  усовершенствовать стратегию.

* Правила создания ботов

Замечание: координаты поля начинаются с единицы!

** Бот расстановщик

Функция, принимает аргументы:

- Конфигурация поля в виде списка длинны и ширины (например '(10 10));

- Конфигурация кораблей в виде их списка в форме размеров (например
  обычная конфигурация '(4 3 3 2 2 2 1 1 1 1))

Возвращает список кораблей в виде '(размер (положение-x положение-y) поворот).

"Поворот" может принимать значения от 1 до (length game-space-config),
и обозначает номер координаты, которая не одинакова для всех клеток,
занятых кораблем.

Например, такое расположение кораблей описывается списком:

#BEGIN_EXAMPLE

'((4 (1 1) 2) (1 (10 10) 1))

 * . . . . . . . . .
 * . . . . . . . . .
 * . . . . . . . . .
 * . . . . . . . . .
 . . . . . . . . . .
 . . . . . . . . . .
 . . . . . . . . . .
 . . . . . . . . . .
 . . . . . . . . . .
 . . . . . . . . . *

#END_EXAMPLE

** Бот стрелóк

Функция, принимает аргументы

- Конфигурация поля в виде списка длины, ширины и т. д. (например '(10 10));

- Конфигурация кораблей в виде списка их размеров (например обычная
  конфигурация '(4 3 3 2 2 2 1 1 1 1))

Возвращает безымянную функцию, которая принимает один необязательный
аргумент --- результат выстрела в виде :missed :shooted или :killed.

Первый вызов безымянной функции происходит без аргумента.

Функция должна выдавать цель стрельбы в виде списка ее координат
(например, '(1 1)).
